### ISSUE TITLE
CI tests broken after merge large contracts and update SDK

### ISSUE THREAD

**Issue by s-medvedev** [Cyber-Core/solana-program-library#72]
CI was broken after merge large contracts (#47) and update SDK (#52) issues (commit 5d59f85).

Possible actions to solve the problem:

- [x] run evm_loader at last node (v1.5.x or v1.6.x).
- [x] increase stack size available to contract (value for linker script and limit in Solana node)
- [ ] check memory allocator used in evm_loader
- [ ] investigate failed CI test
- [ ] check warning on stack size when contract builds
- [ ] check SDK ChangeLog

Failed tests in CI logs:
```
======================================================================
FAIL: test_addReturn (test_event.EventTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/test_event.py", line 92, in test_addReturn
    self.assertEqual(data[2:], bytes().fromhex("%064x" % 0x3))
AssertionError: b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' != b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03'
 
======================================================================
FAIL: test_addReturnEvent (test_event.EventTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/test_event.py", line 111, in test_addReturnEvent
    self.assertEqual(data[2:34], bytes().fromhex('%064x' % 3)) #sum
AssertionError: b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' != b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03'
 
======================================================================
FAIL: test_addReturnEventTwice (test_event.EventTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/test_event.py", line 136, in test_addReturnEventTwice
    self.assertEqual(data[2:34], bytes().fromhex('%064x' % 5)) #sum
AssertionError: b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' != b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05'
 
======================================================================
FAIL: test_events_of_different_instructions (test_event.EventTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/test_event.py", line 181, in test_events_of_different_instructions
    self.assertEqual(data[2:34], bytes().fromhex('%064x' % 0x5)) #sum
AssertionError: b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00' != b'\x0[63 chars]00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x05'
 
----------------------------------------------------------------------
```
Also contract execution under `UniswapV2::Pair getInputPrice:0` broken.
Logs from emulator:
```
backend::new
Not found account for 0xaa4d…4ff1 => DAsfstMtPkpSQKMecmciuvi5EnnQj5y9bdC3xW5fHv1x (seed 3NcRgxaQ1eUh5jEuUcbNzRCjYd1A)
Account found
Account data len 65
Account owner 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW
  SolidityAccount::new
  Get data with length 65
Unpack: 179 1000000000
Not found account for 0xb87b…e4ce => 42SBg8RqXVfxH33bzcK3jLcFsNEUNK1uiLHS2pxisZzJ (seed 3a4uZaBUNBcVE2WfvBEYbk9HeXA5)
Account found
Account data len 20545
Account owner 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW
  SolidityAccount::new
  Get data with length 20545
Unpack: 1 1000000000
Storage data borrowed
Storage data borrowed
Storage data borrowed
Not found account for 0x1bb1…71e1 => 4nS3bzcxxVqDZN7jZAAucBDLW1J4NUYtHX1xJeiHGVQc (seed PNtkQuuAAPqQK7pQZNcokrc1Dov)
Account found
Account data len 5599
Account owner 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW
  SolidityAccount::new
  Get data with length 5599
Unpack: 1 1000000000
Storage data borrowed
Storage data borrowed
Not found account for 0xca1d…e028 => 9zZTAcZ87tDfzC9oYq6MwMLvCuARjrUsoNk7gdgNQXnp (seed 3pKQxwgWeQssS5b6y1nKJLYQTEPy)
Account found
Account data len 5599
Account owner 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW
  SolidityAccount::new
  Get data with length 5599
Unpack: 1 1000000000
Storage data borrowed
Storage data borrowed
Not found account for 0x3f0f…f34c => 2fS4p3rKGjuTqGZbR6NjDpvRa4haC2Zn1A5jJNoB95se (seed sxKeZAfDKLSFqwQcEusBkbrcjym)
Account found
Account data len 16205
Account owner 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW
  SolidityAccount::new
  Get data with length 16205
Unpack: 2 1000000000
Storage data borrowed
Storage data borrowed
Storage data borrowed
Storage data borrowed
Storage data borrowed
Storage data borrowed
Storage data borrowed
Storage data borrowed
Got slot
Slot 839881
Got timestamp
timestamp 1616280422
Storage data borrowed
Call done
Modify: 0x1bb1…71e1 1 1000000000 false
Modify: 0x3f0f…f34c 2 1000000000 false
Modify: 0xaa4d…4ff1 180 1000000000 false
Modify: 0xb87b…e4ce 1 1000000000 false
Modify: 0xca1d…e028 1 1000000000 false
Applies done
succeed
00000000000000000000000000000000000000000000003635c9adc5de9ffc18
[{"address":"0x1bb18e8f758341cfd461648e1f6795f732df71e1","write":"true"},{"address":"0xaa4d6f4ff831181a2bbfd4d62260dabdea964ff1","write":"true"},{"address":"0xb87b116ce5347873d8a5dc765b0079bdb2bae4ce","write":"true"},{"address":"0x3f0f090d3de1ad00923126b681bc1c449199f34c","write":"true"},{"address":"0xca1dbf809f7d1608888d2a855160dfeb255ae028","write":"true"},]
2021-03-22 19:59:48,771 - pid:871888 [D] call_emulated:264 - call_emulated b87b116ce5347873d8a5dc765b0079bdb2bae4ce aa4d6f4ff831181a2bbfd4d62260dabdea964ff1 6a627842000000000000000000000000aa4d6f4ff831181a2bbfd4d62260dabdea964ff1 return {'accounts': [{'address': '0x1bb18e8f758341cfd461648e1f6795f732df71e1', 'new': False, 'writable': True}, {'address': '0xaa4d6f4ff831181a2bbfd4d62260dabdea964ff1', 'new': False, 'writable': True}, {'address': '0xb87b116ce5347873d8a5dc765b0079bdb2bae4ce', 'new': False, 'writable': True}, {'address': '0x3f0f090d3de1ad00923126b681bc1c449199f34c', 'new': False, 'writable': True}, {'address': '0xca1dbf809f7d1608888d2a855160dfeb255ae028', 'new': False, 'writable': True}], 'exit_status': 'succeed', 'result': '00000000000000000000000000000000000000000000003635c9adc5de9ffc18'}
2021-03-22 19:59:48,771 - pid:871888 [D] call_signed:290 - emulator returns: {
   "accounts": [
      {
         "address": "0x1bb18e8f758341cfd461648e1f6795f732df71e1",
         "new": false,
         "writable": true
      },
      {
         "address": "0xaa4d6f4ff831181a2bbfd4d62260dabdea964ff1",
         "new": false,
         "writable": true
      },
      {
         "address": "0xb87b116ce5347873d8a5dc765b0079bdb2bae4ce",
         "new": false,
         "writable": true
      },
      {
         "address": "0x3f0f090d3de1ad00923126b681bc1c449199f34c",
         "new": false,
         "writable": true
      },
      {
         "address": "0xca1dbf809f7d1608888d2a855160dfeb255ae028",
         "new": false,
         "writable": true
      }
   ],
   "exit_status": "succeed",
   "result": "00000000000000000000000000000000000000000000003635c9adc5de9ffc18"
}
```

Logs from evm_loader:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32002,
        "message": "Transaction simulation failed: Error processing Instruction 1: insufficient account keys for instruction",
        "data": {
            "err": {
                "InstructionError": [
                    1,
                    "NotEnoughAccountKeys"
                ]
            },
            "logs": [
                "Program 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW invoke [1]",
                "Program log: Instruction parsed",
                "Program log: do_call",
                "Program log: backend::new",
                "Program log: 0",
                "Program log:   SolidityAccount::new",
                "Program log:   Get data with length 20545",
                "Program log: 1",
                "Program log:   SolidityAccount::new",
                "Program log:   Get data with length 65",
                "Program log: 2",
                "Program log: 3",
                "Program log: 4",
                "Program log:   SolidityAccount::new",
                "Program log:   Get data with length 5599",
                "Program log: 5",
                "Program log:   SolidityAccount::new",
                "Program log:   Get data with length 16205",
                "Program log: 6",
                "Program log:   SolidityAccount::new",
                "Program log:   Get data with length 5599",
                "Program log: 7",
                "Program log: Accounts was read",
                "Program log:   backend initialized",
                "Program log: Executor initialized",
                "Program log:    caller: 0xaa4d\u20264ff1",
                "Program log:  contract: 0xb87b\u2026e4ce",
                "Program log: Found account for 0xaa4d\u20264ff1 on position 2",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xaa4d\u20264ff1 on position 2",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0x1bb1\u202671e1 on position 0",
                "Program log: Found account for 0x1bb1\u202671e1 on position 0",
                "Program log: Found account for 0x1bb1\u202671e1 on position 0",
                "Program log: Found account for 0x1bb1\u202671e1 on position 0",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xca1d\u2026e028 on position 4",
                "Program log: Found account for 0xca1d\u2026e028 on position 4",
                "Program log: Found account for 0xca1d\u2026e028 on position 4",
                "Program log: Found account for 0xca1d\u2026e028 on position 4",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0x3f0f\u2026f34c on position 1",
                "Program log: Found account for 0x3f0f\u2026f34c on position 1",
                "Program log: Found account for 0x3f0f\u2026f34c on position 1",
                "Program log: Found account for 0x3f0f\u2026f34c on position 1",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Storage data borrowed",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Call done",
                "Program log: Succeed execution",
                "Program log: Found account for 0x1bb1\u202671e1 on position 0",
                "Program log: Write account data",
                "Program log: Account updated",
                "Program log: Found account for 0x3f0f\u2026f34c on position 1",
                "Program log: Write account data",
                "Program log: Account updated",
                "Program log: Found account for 0xaa4d\u20264ff1 on position 2",
                "Program log: Write account data",
                "Program log: Account updated",
                "Program log: Found account for 0xb87b\u2026e4ce on position 3",
                "Program log: Write account data",
                "Program log: Update storage",
                "Program log: Storage initialized",
                "Program log: Storage value: 0x0000\u20260000 = 0x0000\u20260000",
                "Program log: Storage value: 0x0000\u20260008 = 0x6056\u20260000",
                "Program log: Storage value: 0x0000\u2026000c = 0x0000\u20260001",
                "Program log: Storage value: 0x13c6\u20269f5b = 0x0000\u2026fc18",
                "Program log: Storage value: 0xa6ee\u2026cb49 = 0x0000\u202603e8",
                "Program log: Account updated",
                "Program log: Not found account for 0xca1d\u2026e4ce",
                "Program log: Total memory occupied: 91006",
                "Program 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW consumed 5256730 of 200000000 compute units",
                "Program 9ETFwASEiTVDBHyvt7yw8yuJ5VLeGwyq4VZ5h1KFHZWW failed: insufficient account keys for instruction"
            ]
        }
    },
    "id": 1540
}
```

**Comment by s-medvedev** [comment]
The problem in BPF SDK. Waiting for an update.
